language: swift
osx_image: xcode8
env:
- LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
- gem install xcpretty -N
script:
- set -o pipefail
- xcodebuild -project SuperRecord.xcodeproj -scheme "SuperRecord" -sdk iphonesimulator
  -destination "platform=iOS Simulator,name=iPhone 6" ONLY_ACTIVE_ARCH=NO  test | xcpretty -c
